import { pgTable, text, integer, boolean, bigint, varchar, jsonb, timestamp, index } from "drizzle-orm/pg-core";

// ============================================================
// Courses, Lessons, Topics
// ============================================================

export const courses = pgTable("courses", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  thumbnail: text("thumbnail").default(""),
  instructor: text("instructor").notNull(),
  price: integer("price").default(0),
  currency: text("currency").default("SAR"),
  duration: integer("duration").default(0),
  level: varchar("level", { length: 20 }).default("Beginner"),
  rating: integer("rating").default(0),
  progress: integer("progress").default(0),
  category: text("category").default(""),
  subject: text("subject").default(""),
  pathId: text("path_id"),
  subjectId: text("subject_id"),
  sectionId: text("section_id"),
  features: text("features").array().default([]),
  description: text("description").default(""),
  instructorBio: text("instructor_bio").default(""),
  modules: jsonb("modules").default([]),
  isPublished: boolean("is_published").default(false),
  showOnPlatform: boolean("show_on_platform").default(true),
  isPackage: boolean("is_package").default(false),
  packageType: varchar("package_type", { length: 20 }),
  packageContentTypes: text("package_content_types").array(),
  originalPrice: integer("original_price"),
  includedCourses: text("included_courses").array().default([]),
  prerequisiteCourseIds: text("prerequisite_course_ids").array().default([]),
  dripContentEnabled: boolean("drip_content_enabled").default(false),
  certificateEnabled: boolean("certificate_enabled").default(false),
  skills: text("skills").array().default([]),
  studentCount: integer("student_count"),
  weeksCount: integer("weeks_count"),
  previewVideoUrl: text("preview_video_url"),
  files: jsonb("files").default([]),
  qa: jsonb("qa").default([]),
  // Content workflow
  ownerType: varchar("owner_type", { length: 20 }).default("platform"),
  ownerId: text("owner_id").default(""),
  createdBy: text("created_by").default(""),
  assignedTeacherId: text("assigned_teacher_id").default(""),
  approvalStatus: varchar("approval_status", { length: 20 }).default("draft"),
  approvedBy: text("approved_by").default(""),
  approvedAt: bigint("approved_at", { mode: "number" }),
  reviewerNotes: text("reviewer_notes").default(""),
  revenueSharePercentage: integer("revenue_share_percentage"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => [
  index("idx_courses_path_id").on(table.pathId),
  index("idx_courses_subject_id").on(table.subjectId),
  index("idx_courses_is_published").on(table.isPublished),
  index("idx_courses_approval_status").on(table.approvalStatus),
  index("idx_courses_owner_type").on(table.ownerType),
  index("idx_courses_owner_id").on(table.ownerId),
]);

export const lessons = pgTable("lessons", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  description: text("description").default(""),
  pathId: text("path_id"),
  subjectId: text("subject_id"),
  sectionId: text("section_id"),
  type: varchar("type", { length: 20 }).notNull(),
  duration: text("duration").default(""),
  content: text("content").default(""),
  videoUrl: text("video_url").default(""),
  fileUrl: text("file_url").default(""),
  meetingUrl: text("meeting_url").default(""),
  meetingDate: text("meeting_date").default(""),
  recordingUrl: text("recording_url").default(""),
  joinInstructions: text("join_instructions").default(""),
  showRecordingOnPlatform: boolean("show_recording_on_platform").default(false),
  showOnPlatform: boolean("show_on_platform").default(true),
  quizId: text("quiz_id"),
  order: integer("order").default(0),
  isLocked: boolean("is_locked").default(false),
  skillIds: text("skill_ids").array().default([]),
  // Content workflow
  ownerType: varchar("owner_type", { length: 20 }).default("platform"),
  ownerId: text("owner_id").default(""),
  createdBy: text("created_by").default(""),
  assignedTeacherId: text("assigned_teacher_id").default(""),
  approvalStatus: varchar("approval_status", { length: 20 }).default("draft"),
  approvedBy: text("approved_by").default(""),
  approvedAt: bigint("approved_at", { mode: "number" }),
  reviewerNotes: text("reviewer_notes").default(""),
  revenueSharePercentage: integer("revenue_share_percentage"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
}, (table) => [
  index("idx_lessons_path_id").on(table.pathId),
  index("idx_lessons_subject_id").on(table.subjectId),
  index("idx_lessons_quiz_id").on(table.quizId),
  index("idx_lessons_approval_status").on(table.approvalStatus),
  index("idx_lessons_owner_type").on(table.ownerType),
]);

export const topics = pgTable("topics", {
  id: text("id").primaryKey(),
  pathId: text("path_id").notNull(),
  subjectId: text("subject_id").notNull(),
  sectionId: text("section_id"),
  title: text("title").notNull(),
  parentId: text("parent_id"),
  order: integer("order").default(0),
  showOnPlatform: boolean("show_on_platform").default(true),
  isLocked: boolean("is_locked").default(false),
  lessonIds: text("lesson_ids").array().default([]),
  quizIds: text("quiz_ids").array().default([]),
}, (table) => [
  index("idx_topics_path_id").on(table.pathId),
  index("idx_topics_subject_id").on(table.subjectId),
  index("idx_topics_parent_id").on(table.parentId),
]);
